#!/bin/bash

nitrogen --restore
setxkbmap -option ctrl:nocaps
xcompmgr -c -C -f -F -t-5 -l-5 -r4.2 -o.55 &
xrdb -merge ~/.Xresources
xsetroot -cursor_name left_ptr

sleep 0.5
case $(hostnamectl --static) in
	ireland)
		polybar --reload ireland-primary &
		numlockx on
		pasystray &
		;;
	wisp)
		polybar --reload wisp &
		;;
esac
