#!/bin/bash

nitrogen --restore
setxkbmap -option ctrl:nocaps
xcompmgr -c -C -f -F -t-5 -l-5 -r4.2 -o.55 &
xrdb -merge ~/.Xresources
xsetroot -cursor_name left_ptr

case $(hostname) in
	wisp)
		polybar --reload wisp &
		;;
	ganymede)
		polybar --reload ganymede-primary &
		polybar --reload ganymede-secondary &
		numlockx on
		;;
esac
