#!/usr/bin/env bash

bspc config border_width          2
bspc config window_gap            8
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config focus_follows_pointer true
bspc config gapless_monocle       true
bspc config single_monocle        true

# Colors
bspc config focused_border_color         '#268BD2'
bspc config presel_feedback_color        '#222222'

# Desktop names
#          
for MONITOR in $(bspc query -M); do
	bspc monitor ${MONITOR} --reset-desktops \
		$(echo -e ) \
		$(echo -e ) \
		$(echo -e ) \
		$(echo -e ) \
		$(echo -e ) \
		$(echo -e ) \
		$(echo -e ) \
		$(echo -e ) \
		$(echo -e ) \
		$(echo -e )
done

# Rules
bspc rule --add crx_gaedmjdfmmahhbjefcbgaolhhanlaolb floating=on # Authy Extension
bspc rule --add crx_nckgahadagoaajjgafhacjanaoiihapd floating=on # Hangouts Extension
bspc rule --add Gimp follow=on floating=on
bspc rule --add libreoffice manage=on state=tiled
bspc rule --add '*:soffice' manage=on state=tiled
bspc rule --add mpv floating=on
bspc rule --add rdesktop manage=on border=off pseudo_tiled=on
