#!/usr/bin/env bash

bspc config border_width          2
bspc config window_gap            14
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config focus_follows_pointer true
bspc config gapless_monocle       true
bspc config single_monocle        true

# Colors
bspc config focused_border_color  '#5E81AC'
bspc config presel_feedback_color '#4C566A'

# Desktop names
#          
for MONITOR in $(bspc query -M); do
	bspc monitor ${MONITOR} --reset-desktops \
		$(echo -e ) \
		$(echo -e ) \
		$(echo -e ) \
		$(echo -e ) \
		$(echo -e ) \
		$(echo -e ) \
		$(echo -e ) \
		$(echo -e ) \
		$(echo -e ) \
		$(echo -e )
done

# Rules
bspc rule --add Chromium:crx_gaedmjdfmmahhbjefcbgaolhhanlaolb state=floating # Authy Extension
bspc rule --add mpv state=floating
